#define TK_OPEN                             1
#define TK_LPAREN                           2
#define TK_SEMICOL                          3
#define TK_UNTIL                            4
#define TK_DO                               5
#define TK_END                              6
#define TK_WHILE                            7
#define TK_REPEAT                           8
#define TK_IF                               9
#define TK_FUNCTION                        10
#define TK_SET                             11
#define TK_FOR                             12
#define TK_NAME                            13
#define TK_IN                              14
#define TK_ELSE                            15
#define TK_ELSEIF                          16
#define TK_THEN                            17
#define TK_BREAK                           18
#define TK_RETURN                          19
#define TK_LOCAL                           20
#define TK_COLON                           21
#define TK_DOT                             22
#define TK_COMMA                           23
#define TK_OR                              24
#define TK_AND                             25
#define TK_L                               26
#define TK_LE                              27
#define TK_G                               28
#define TK_GE                              29
#define TK_EQ                              30
#define TK_NE                              31
#define TK_CONCAT                          32
#define TK_PLUS                            33
#define TK_MINUS                           34
#define TK_TIMES                           35
#define TK_DIVIDE                          36
#define TK_MOD                             37
#define TK_NOT                             38
#define TK_HASH                            39
#define TK_POW                             40
#define TK_NIL                             41
#define TK_TRUE                            42
#define TK_FALSE                           43
#define TK_DOTS                            44
#define TK_NUMBER                          45
#define TK_STRING                          46
#define TK_SLPAREN                         47
#define TK_SRPAREN                         48
#define TK_RPAREN                          49
#define TK_LBRACE                          50
#define TK_RBRACE                          51
