#define TK_SEMICOL                          1
#define TK_UNTIL                            2
#define TK_DO                               3
#define TK_END                              4
#define TK_WHILE                            5
#define TK_REPEAT                           6
#define TK_IF                               7
#define TK_FUNCTION                         8
#define TK_SET                              9
#define TK_FOR                             10
#define TK_NAME                            11
#define TK_IN                              12
#define TK_ELSE                            13
#define TK_ELSEIF                          14
#define TK_THEN                            15
#define TK_BREAK                           16
#define TK_RETURN                          17
#define TK_LOCAL                           18
#define TK_COLON                           19
#define TK_DOT                             20
#define TK_COMMA                           21
#define TK_OR                              22
#define TK_AND                             23
#define TK_L                               24
#define TK_LE                              25
#define TK_G                               26
#define TK_GE                              27
#define TK_EQ                              28
#define TK_NE                              29
#define TK_CONCAT                          30
#define TK_PLUS                            31
#define TK_MINUS                           32
#define TK_TIMES                           33
#define TK_DIVIDE                          34
#define TK_MOD                             35
#define TK_NOT                             36
#define TK_HASH                            37
#define TK_POW                             38
#define TK_NIL                             39
#define TK_TRUE                            40
#define TK_FALSE                           41
#define TK_DOTS                            42
#define TK_NUMBER                          43
#define TK_STRING                          44
#define TK_SLPAREN                         45
#define TK_SRPAREN                         46
#define TK_LPAREN                          47
#define TK_RPAREN                          48
#define TK_LBRACE                          49
#define TK_RBRACE                          50
